"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = EcommerceMetrics;
var jsx_runtime_1 = require("react/jsx-runtime");
var icons_1 = require("../../icons");
var Badge_1 = require("../ui/badge/Badge");
function EcommerceMetrics() {
    return ((0, jsx_runtime_1.jsxs)("div", { className: "grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-6", children: [(0, jsx_runtime_1.jsxs)("div", { className: "rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03] md:p-6", children: [(0, jsx_runtime_1.jsx)("div", { className: "flex items-center justify-center w-12 h-12 bg-gray-100 rounded-xl dark:bg-gray-800", children: (0, jsx_runtime_1.jsx)(icons_1.GroupIcon, { className: "text-gray-800 size-6 dark:text-white/90" }) }), (0, jsx_runtime_1.jsxs)("div", { className: "flex items-end justify-between mt-5", children: [(0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)("span", { className: "text-sm text-gray-500 dark:text-gray-400", children: "Customers" }), (0, jsx_runtime_1.jsx)("h4", { className: "mt-2 font-bold text-gray-800 text-title-sm dark:text-white/90", children: "3,782" })] }), (0, jsx_runtime_1.jsxs)(Badge_1.default, { color: "success", children: [(0, jsx_runtime_1.jsx)(icons_1.ArrowUpIcon, {}), "11.01%"] })] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03] md:p-6", children: [(0, jsx_runtime_1.jsx)("div", { className: "flex items-center justify-center w-12 h-12 bg-gray-100 rounded-xl dark:bg-gray-800", children: (0, jsx_runtime_1.jsx)(icons_1.BoxIconLine, { className: "text-gray-800 size-6 dark:text-white/90" }) }), (0, jsx_runtime_1.jsxs)("div", { className: "flex items-end justify-between mt-5", children: [(0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)("span", { className: "text-sm text-gray-500 dark:text-gray-400", children: "Orders" }), (0, jsx_runtime_1.jsx)("h4", { className: "mt-2 font-bold text-gray-800 text-title-sm dark:text-white/90", children: "5,359" })] }), (0, jsx_runtime_1.jsxs)(Badge_1.default, { color: "error", children: [(0, jsx_runtime_1.jsx)(icons_1.ArrowDownIcon, {}), "9.05%"] })] })] })] }));
}
