"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = Alerts;
var jsx_runtime_1 = require("react/jsx-runtime");
var PageBreadCrumb_1 = require("../../components/common/PageBreadCrumb");
var ComponentCard_1 = require("../../components/common/ComponentCard");
var Alert_1 = require("../../components/ui/alert/Alert");
var PageMeta_1 = require("../../components/common/PageMeta");
function Alerts() {
    return ((0, jsx_runtime_1.jsxs)(jsx_runtime_1.Fragment, { children: [(0, jsx_runtime_1.jsx)(PageMeta_1.default, { title: "React.js Alerts Dashboard | TailAdmin - React.js Admin Dashboard Template", description: "This is React.js Alerts Dashboard page for TailAdmin - React.js Tailwind CSS Admin Dashboard Template" }), (0, jsx_runtime_1.jsx)(PageBreadCrumb_1.default, { pageTitle: "Alerts" }), (0, jsx_runtime_1.jsxs)("div", { className: "space-y-5 sm:space-y-6", children: [(0, jsx_runtime_1.jsxs)(ComponentCard_1.default, { title: "Success Alert", children: [(0, jsx_runtime_1.jsx)(Alert_1.default, { variant: "success", title: "Success Message", message: "Be cautious when performing this action.", showLink: true, linkHref: "/", linkText: "Learn more" }), (0, jsx_runtime_1.jsx)(Alert_1.default, { variant: "success", title: "Success Message", message: "Be cautious when performing this action.", showLink: false })] }), (0, jsx_runtime_1.jsxs)(ComponentCard_1.default, { title: "Warning Alert", children: [(0, jsx_runtime_1.jsx)(Alert_1.default, { variant: "warning", title: "Warning Message", message: "Be cautious when performing this action.", showLink: true, linkHref: "/", linkText: "Learn more" }), (0, jsx_runtime_1.jsx)(Alert_1.default, { variant: "warning", title: "Warning Message", message: "Be cautious when performing this action.", showLink: false })] }), " ", (0, jsx_runtime_1.jsxs)(ComponentCard_1.default, { title: "Error Alert", children: [(0, jsx_runtime_1.jsx)(Alert_1.default, { variant: "error", title: "Error Message", message: "Be cautious when performing this action.", showLink: true, linkHref: "/", linkText: "Learn more" }), (0, jsx_runtime_1.jsx)(Alert_1.default, { variant: "error", title: "Error Message", message: "Be cautious when performing this action.", showLink: false })] }), " ", (0, jsx_runtime_1.jsxs)(ComponentCard_1.default, { title: "Info Alert", children: [(0, jsx_runtime_1.jsx)(Alert_1.default, { variant: "info", title: "Info Message", message: "Be cautious when performing this action.", showLink: true, linkHref: "/", linkText: "Learn more" }), (0, jsx_runtime_1.jsx)(Alert_1.default, { variant: "info", title: "Info Message", message: "Be cautious when performing this action.", showLink: false })] })] })] }));
}
